{
  # ══════════════════════════════════════════════════════════════════
  #  EIAMS — Enterprise Inventory & Asset Management System
  #  NixOS Flake — Production Deployment
  #
  #  Usage:
  #    nixos-rebuild switch --flake .#eiams-server
  #    nix develop          (enter dev shell)
  # ══════════════════════════════════════════════════════════════════
  description = "EIAMS Django Application — NixOS Production Flake";

  inputs = {
    nixpkgs.url     = "github:NixOS/nixpkgs/nixos-24.05";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    let
      system  = "x86_64-linux";
      pkgs    = nixpkgs.legacyPackages.${system};
    in
    {
      # ── NixOS system configuration ─────────────────────────────────
      nixosConfigurations.eiams-server = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          ./hardware-configuration.nix   # auto-generated by nixos-generate-config
          ./configuration.nix
          ./modules/eiams-service.nix
        ];
        specialArgs = { inherit self; };
      };

      # ── Development shell ──────────────────────────────────────────
      devShells.${system}.default = pkgs.mkShell {
        name = "eiams-dev";
        buildInputs = with pkgs; [
          python312
          python312Packages.pip
          python312Packages.virtualenv
          python312Packages.pillow
          python312Packages.django
          sqlite
          zlib
          libjpeg
          libpng
          gcc
          gnumake
          nodePackages.npm
          git
          just           # task runner (optional)
        ];
        shellHook = ''
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "  EIAMS Development Shell"
          echo "  Python: $(python --version)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Auto-create and activate venv
          if [ ! -d .venv ]; then
            python -m venv .venv
            echo "Created .venv"
          fi
          source .venv/bin/activate
          pip install --quiet -r requirements.txt
          echo "  Virtualenv: .venv (activated)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "  Commands: python manage.py runserver"
          echo "            python manage.py migrate"
          echo "            python manage.py seed_data"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        '';
      };
    };
}
