#!/usr/bin/env python
"""
Django's command-line utility for administrative tasks.
This file is automatically generated by Django and provides
an entry point to all Django management commands.

Usage:
    python manage.py runserver             → Start development server
    python manage.py makemigrations        → Create new migrations
    python manage.py migrate               → Apply migrations
    python manage.py createsuperuser       → Create admin user
    python manage.py collectstatic         → Gather static files
    python manage.py test                  → Run tests
"""
import os
import sys


def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'inventory_system.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()
