# Generated by Django 6.0.5 on 2026-07-24 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.IntegerField(verbose_name='Quantity at Alert Time')),
                ('min_qty', models.IntegerField(verbose_name='Minimum Threshold')),
                ('alert_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Alert Date')),
                ('status', models.CharField(choices=[('New', 'New'), ('Resolved', 'Resolved')], default='New', max_length=20, verbose_name='Alert Status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='inventory.inventoryitem', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name': 'Low Stock Alert',
                'verbose_name_plural': 'Low Stock Alerts',
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Stock IN', 'Stock IN'), ('Stock OUT', 'Stock OUT'), ('Adjustment', 'Adjustment'), ('Purchase', 'Purchase'), ('Usage', 'Usage'), ('Damage', 'Damage'), ('Lost', 'Lost'), ('Expired', 'Expired'), ('Transfer', 'Transfer')], max_length=20, verbose_name='Movement Type')),
                ('quantity', models.IntegerField(help_text='Positive integer quantity for this movement', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Movement Date')),
                ('reference_no', models.CharField(blank=True, help_text='PO number, invoice number, or internal reference', max_length=100, null=True, verbose_name='Reference Number')),
                ('reason', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Usage', 'Usage'), ('Damage', 'Damage'), ('Adjustment', 'Adjustment'), ('Loss', 'Loss'), ('Expired', 'Expired'), ('Transfer', 'Transfer'), ('Other', 'Other')], max_length=150, null=True, verbose_name='Reason')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('qty_after', models.IntegerField(blank=True, null=True, verbose_name='Quantity After Movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventoryitem', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-movement_date'],
            },
        ),
    ]
