# Generated by Django 6.0.5 on 2026-07-24 08:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150, unique=True, verbose_name='Location Name')),
                ('location_type', models.CharField(choices=[('Warehouse', 'Warehouse'), ('Office', 'Office'), ('Building', 'Building'), ('Department', 'Department'), ('Branch', 'Branch')], max_length=50, verbose_name='Location Type')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Physical Address')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Display name of the category', max_length=100, verbose_name='Category Name')),
                ('category_type', models.CharField(choices=[('Inventory', 'Inventory'), ('Asset', 'Asset')], help_text='Inventory category or Asset category', max_length=50, verbose_name='Category Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
                'unique_together': {('category_name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='Unique system-generated or manually assigned item code', max_length=50, unique=True, verbose_name='Item Code')),
                ('barcode', models.CharField(blank=True, help_text='Code128 barcode value', max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('item_name', models.CharField(max_length=150, verbose_name='Item Name')),
                ('unit', models.CharField(help_text='e.g., pcs, box, kg, liter, set', max_length=50, verbose_name='Unit of Measure')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purchase Price')),
                ('current_qty', models.IntegerField(default=0, help_text='Real-time stock quantity', verbose_name='Current Quantity')),
                ('min_qty', models.IntegerField(default=0, help_text='Low-stock alert triggers when current_qty ≤ this value', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Quantity')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'category_type': 'Inventory', 'status': 'Active'}, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['item_name'],
            },
        ),
    ]
