# Generated by Django 6.0.5 on 2026-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_name_km',
            field=models.CharField(blank=True, help_text='Item name in Khmer — shown when language is set to Khmer', max_length=200, null=True, verbose_name='ឈ្មោះទំនិញ (ខ្មែរ)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_name',
            field=models.CharField(max_length=150, verbose_name='Item Name (English)'),
        ),
    ]
