# Generated by Django 6.0.5 on 2026-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_item_name_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product photo (JPG/PNG, max 5MB)', null=True, upload_to='inventory/items/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External product image URL (used when no local image is uploaded)', max_length=500, null=True, verbose_name='Product Image URL'),
        ),
    ]
