# Generated by Django 6.0.5 on 2026-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/', verbose_name='Asset Image'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.URLField(blank=True, help_text='External product image URL', max_length=500, null=True, verbose_name='Asset Image URL'),
        ),
    ]
